#!/usr/bin/env perl

use 5.014;
use strict;
use warnings;
use Attribute::Constant;
use App::DoThis;

my $APP_NAME : Constant('dothis');

# die "Growl cannot be detected\n" unless growl_installed;
die "Growl is not running\n" unless growl_running;

register_application($APP_NAME);
dothis @ARGV;
